language: php

php:
  - 7.0
  - 7.1


before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.xml tests/

notifications:
  email: false
  slack:
    secure: lw3BSirBDzoZbnksnyDVj+MQ1ei2crDYZfd75T9OtwYP+x1oXnWgn+/a7Bl5D+kg46S6tmUCrVg8Y4WqKTFxVsffatckPTmCHRqTC2DWxNT83xYvc7H8aBVW3rG8Zj8iNAe1SbuQnF0z083ndCP/Hi7xjg7u2Fuvmn8x8tMOanj4hR3lVSdrIDUmXtkCNCBWlZc3jBvqVuXrkKQKFMGQqpJYZiKWrY5VmcztJxVMUP4dwYTRUkDHmbDyw2KMNyoeVXjsIynILYWmupkkt8B7j7D6D5+XUYKsbdLzj3NuGSd0RX4CDvYqQLf3NlUMhAgOzvmvOeoIz10FKgDTQN2kFixx+MrghGO6TEY+Fe50ahh+Bd2N5xISQmTbgsO4VBR0jBI8zhfr3SA4gop7kdbTFZU5Exda5BqtVgiiMryMgLq+n7hGCl/Ni+pRxB2z/G214JeCV8fykX4LZp+ta3kKodtZbfkPN+pDRDWET0yXZwjEIy2yDLFd2o/IcpH/Er6j3OqTo//XJu0y7UQ7oSi4Nb1TzqnkVKi99QrqQsuOmcWPRS9tPjiTZPNUmqc1JDWO5NazEAgMT5/mbzAgsfGp/WBNMAM5QYQNfl5d1O33eDQsqc3/AXA9SGhyvAb/chDR7lsgIQbE6PwQqLNtInBtFGmKJpq/Y2PhCREFHIfoUzU=
